//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CentumWebApplication.FCXService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FCXSoapBinding", Namespace="http://services.axis.fxportal.hermes.filogix.com")]
    public partial class FCXService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback acknowledgeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessage1OperationCompleted;
        
        private System.Threading.SendOrPostCallback setMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FCXService() {
            this.Url = global::CentumWebApplication.Properties.Settings.Default.CentumWebApplication_FCXService_FCXService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event acknowledgeCompletedEventHandler acknowledgeCompleted;
        
        /// <remarks/>
        public event getMessageCompletedEventHandler getMessageCompleted;
        
        /// <remarks/>
        public event getMessage1CompletedEventHandler getMessage1Completed;
        
        /// <remarks/>
        public event setMessageCompletedEventHandler setMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.axis.fxportal.hermes.filogix.com", ResponseNamespace="http://services.axis.fxportal.hermes.filogix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void acknowledge(Response response) {
            this.Invoke("acknowledge", new object[] {
                        response});
        }
        
        /// <remarks/>
        public void acknowledgeAsync(Response response) {
            this.acknowledgeAsync(response, null);
        }
        
        /// <remarks/>
        public void acknowledgeAsync(Response response, object userState) {
            if ((this.acknowledgeOperationCompleted == null)) {
                this.acknowledgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacknowledgeOperationCompleted);
            }
            this.InvokeAsync("acknowledge", new object[] {
                        response}, this.acknowledgeOperationCompleted, userState);
        }
        
        private void OnacknowledgeOperationCompleted(object arg) {
            if ((this.acknowledgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acknowledgeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.axis.fxportal.hermes.filogix.com", ResponseNamespace="http://services.axis.fxportal.hermes.filogix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMessageReturn")]
        public VersionedMessage getMessage(string channel) {
            object[] results = this.Invoke("getMessage", new object[] {
                        channel});
            return ((VersionedMessage)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageAsync(string channel) {
            this.getMessageAsync(channel, null);
        }
        
        /// <remarks/>
        public void getMessageAsync(string channel, object userState) {
            if ((this.getMessageOperationCompleted == null)) {
                this.getMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageOperationCompleted);
            }
            this.InvokeAsync("getMessage", new object[] {
                        channel}, this.getMessageOperationCompleted, userState);
        }
        
        private void OngetMessageOperationCompleted(object arg) {
            if ((this.getMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageCompleted(this, new getMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="getMessage1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestElementName="getMessage", RequestNamespace="http://services.axis.fxportal.hermes.filogix.com", ResponseElementName="getMessageResponse", ResponseNamespace="http://services.axis.fxportal.hermes.filogix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMessageReturn")]
        public VersionedMessage getMessage(string channel, string clientFormat, string clientVersion) {
            object[] results = this.Invoke("getMessage1", new object[] {
                        channel,
                        clientFormat,
                        clientVersion});
            return ((VersionedMessage)(results[0]));
        }
        
        /// <remarks/>
        public void getMessage1Async(string channel, string clientFormat, string clientVersion) {
            this.getMessage1Async(channel, clientFormat, clientVersion, null);
        }
        
        /// <remarks/>
        public void getMessage1Async(string channel, string clientFormat, string clientVersion, object userState) {
            if ((this.getMessage1OperationCompleted == null)) {
                this.getMessage1OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessage1OperationCompleted);
            }
            this.InvokeAsync("getMessage1", new object[] {
                        channel,
                        clientFormat,
                        clientVersion}, this.getMessage1OperationCompleted, userState);
        }
        
        private void OngetMessage1OperationCompleted(object arg) {
            if ((this.getMessage1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessage1Completed(this, new getMessage1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.axis.fxportal.hermes.filogix.com", ResponseNamespace="http://services.axis.fxportal.hermes.filogix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("setMessageReturn")]
        public Response setMessage(VersionedMessage message) {
            object[] results = this.Invoke("setMessage", new object[] {
                        message});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void setMessageAsync(VersionedMessage message) {
            this.setMessageAsync(message, null);
        }
        
        /// <remarks/>
        public void setMessageAsync(VersionedMessage message, object userState) {
            if ((this.setMessageOperationCompleted == null)) {
                this.setMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMessageOperationCompleted);
            }
            this.InvokeAsync("setMessage", new object[] {
                        message}, this.setMessageOperationCompleted, userState);
        }
        
        private void OnsetMessageOperationCompleted(object arg) {
            if ((this.setMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMessageCompleted(this, new setMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://packaging.common.hermes.filogix.com")]
    public partial class Response {
        
        private string messageIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://packaging.common.hermes.filogix.com")]
    public partial class VersionedDocument {
        
        private byte[] contentField;
        
        private string docnameField;
        
        private string formatField;
        
        private string mimetypeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string docname {
            get {
                return this.docnameField;
            }
            set {
                this.docnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://packaging.common.hermes.filogix.com")]
    public partial class VersionedMessage {
        
        private string dealIdField;
        
        private VersionedDocument[] documentsField;
        
        private string formatField;
        
        private string messageIdField;
        
        private string receiverField;
        
        private string senderField;
        
        private System.Nullable<System.DateTime> timestampField;
        
        private string transactionField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VersionedDocument[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void acknowledgeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getMessageCompletedEventHandler(object sender, getMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionedMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionedMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getMessage1CompletedEventHandler(object sender, getMessage1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessage1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessage1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionedMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionedMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setMessageCompletedEventHandler(object sender, setMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591