//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormPropertyInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormPropertyInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentumWebApplication.App_GlobalResources.FormPropertyInfo", typeof(FormPropertyInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment High Rise.
        /// </summary>
        public static string apartmentHighRise {
            get {
                return ResourceManager.GetString("apartmentHighRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Low Rise.
        /// </summary>
        public static string apartmentLowRise {
            get {
                return ResourceManager.GetString("apartmentLowRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached.
        /// </summary>
        public static string attached {
            get {
                return ResourceManager.GetString("attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Level.
        /// </summary>
        public static string biLevel {
            get {
                return ResourceManager.GetString("biLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detached.
        /// </summary>
        public static string detached {
            get {
                return ResourceManager.GetString("detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string doubleGarage {
            get {
                return ResourceManager.GetString("doubleGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex Detatched.
        /// </summary>
        public static string duplexDetached {
            get {
                return ResourceManager.GetString("duplexDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duples Semi Detatched.
        /// </summary>
        public static string duplexSemiDetached {
            get {
                return ResourceManager.GetString("duplexSemiDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwelling Style:.
        /// </summary>
        public static string dwellingStyle {
            get {
                return ResourceManager.GetString("dwellingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Monthly Condo Fees:.
        /// </summary>
        public static string estimatedMonthlyCondoFees {
            get {
                return ResourceManager.GetString("estimatedMonthlyCondoFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Monthly Heating:.
        /// </summary>
        public static string estimatedMonthlyHeating {
            get {
                return ResourceManager.GetString("estimatedMonthlyHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Annual Property Taxes:.
        /// </summary>
        public static string estimatedPropertyTaxes {
            get {
                return ResourceManager.GetString("estimatedPropertyTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Plex Detached.
        /// </summary>
        public static string fourPlexDetached {
            get {
                return ResourceManager.GetString("fourPlexDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Plex Semi-Detached.
        /// </summary>
        public static string fourPlexSemiDetached {
            get {
                return ResourceManager.GetString("fourPlexSemiDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Ft {
            get {
                return ResourceManager.GetString("Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Size:.
        /// </summary>
        public static string garageSize {
            get {
                return ResourceManager.GetString("garageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Type:.
        /// </summary>
        public static string garageType {
            get {
                return ResourceManager.GetString("garageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liveable Area Units:.
        /// </summary>
        public static string livableAreaUnits {
            get {
                return ResourceManager.GetString("livableAreaUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liveable Area:.
        /// </summary>
        public static string liveableArea {
            get {
                return ResourceManager.GetString("liveableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Area:.
        /// </summary>
        public static string lotArea {
            get {
                return ResourceManager.GetString("lotArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Depth:.
        /// </summary>
        public static string lotDepth {
            get {
                return ResourceManager.GetString("lotDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Width:.
        /// </summary>
        public static string lotWidth {
            get {
                return ResourceManager.GetString("lotWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Home Detached.
        /// </summary>
        public static string modularHomeDetached {
            get {
                return ResourceManager.GetString("modularHomeDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Home Semi-Detached.
        /// </summary>
        public static string modularHomeSemiDetached {
            get {
                return ResourceManager.GetString("modularHomeSemiDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string noneGarage {
            get {
                return ResourceManager.GetString("noneGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied By:.
        /// </summary>
        public static string occupiedBy {
            get {
                return ResourceManager.GetString("occupiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Storey.
        /// </summary>
        public static string oneStorey {
            get {
                return ResourceManager.GetString("oneStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Occupied.
        /// </summary>
        public static string ownerOccupied {
            get {
                return ResourceManager.GetString("ownerOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Occupied &amp; Rental.
        /// </summary>
        public static string ownerOccupiedRental {
            get {
                return ResourceManager.GetString("ownerOccupiedRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type:.
        /// </summary>
        public static string propertyType {
            get {
                return ResourceManager.GetString("propertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string rental {
            get {
                return ResourceManager.GetString("rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Housing.
        /// </summary>
        public static string rowHousing {
            get {
                return ResourceManager.GetString("rowHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Home.
        /// </summary>
        public static string secondHome {
            get {
                return ResourceManager.GetString("secondHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-Detached.
        /// </summary>
        public static string semiDetached {
            get {
                return ResourceManager.GetString("semiDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string singleGarage {
            get {
                return ResourceManager.GetString("singleGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Level.
        /// </summary>
        public static string splitLevel {
            get {
                return ResourceManager.GetString("splitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sq Ft.
        /// </summary>
        public static string sqFt {
            get {
                return ResourceManager.GetString("sqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sq M.
        /// </summary>
        public static string sqM {
            get {
                return ResourceManager.GetString("sqM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked.
        /// </summary>
        public static string stacked {
            get {
                return ResourceManager.GetString("stacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storey and a Half.
        /// </summary>
        public static string storeyAndAHalf {
            get {
                return ResourceManager.GetString("storeyAndAHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Storey.
        /// </summary>
        public static string threeStorey {
            get {
                return ResourceManager.GetString("threeStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri-Plex Detached.
        /// </summary>
        public static string triPlexDetached {
            get {
                return ResourceManager.GetString("triPlexDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri-Plex Semi-Detached.
        /// </summary>
        public static string triPlexSemiDetached {
            get {
                return ResourceManager.GetString("triPlexSemiDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple.
        /// </summary>
        public static string trippleGarage {
            get {
                return ResourceManager.GetString("trippleGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Storey.
        /// </summary>
        public static string twoStorey {
            get {
                return ResourceManager.GetString("twoStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units:.
        /// </summary>
        public static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
    }
}
