//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormQualifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormQualifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentumWebApplication.App_GlobalResources.FormQualifiers", typeof(FormQualifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will you be adding a co-applicant?.
        /// </summary>
        public static string coApplicant {
            get {
                return ResourceManager.GetString("coApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Funds Required:.
        /// </summary>
        public static string dateFundsRequired {
            get {
                return ResourceManager.GetString("dateFundsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficiency Sale.
        /// </summary>
        public static string deficiencySale {
            get {
                return ResourceManager.GetString("deficiencySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETO.
        /// </summary>
        public static string eto {
            get {
                return ResourceManager.GetString("eto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Amount Required:.
        /// </summary>
        public static string mortgageAmountRequired {
            get {
                return ResourceManager.GetString("mortgageAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase + Improvements.
        /// </summary>
        public static string purchaseImprovements {
            get {
                return ResourceManager.GetString("purchaseImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Loan:.
        /// </summary>
        public static string purposeOfLoan {
            get {
                return ResourceManager.GetString("purposeOfLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinance.
        /// </summary>
        public static string refinance {
            get {
                return ResourceManager.GetString("refinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch / Transfer.
        /// </summary>
        public static string switchTransfer {
            get {
                return ResourceManager.GetString("switchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        public static string workout {
            get {
                return ResourceManager.GetString("workout", resourceCulture);
            }
        }
    }
}
