//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormFinancialInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormFinancialInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentumWebApplication.App_GlobalResources.FormFinancialInfo", typeof(FormFinancialInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spousal Support.
        /// </summary>
        public static string alimonySupport {
            get {
                return ResourceManager.GetString("alimonySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount owing on current mortgage(s) - 1.
        /// </summary>
        public static string amountOwingOnCurrentMortgage1 {
            get {
                return ResourceManager.GetString("amountOwingOnCurrentMortgage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount owing on current mortgage(s) - 2.
        /// </summary>
        public static string amountOwingOnCurrentMortgage2 {
            get {
                return ResourceManager.GetString("amountOwingOnCurrentMortgage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lease.
        /// </summary>
        public static string autoLease {
            get {
                return ResourceManager.GetString("autoLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile: Present Value.
        /// </summary>
        public static string automobilePresentValue {
            get {
                return ResourceManager.GetString("automobilePresentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Savings.
        /// </summary>
        public static string cashSavings {
            get {
                return ResourceManager.GetString("cashSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Support.
        /// </summary>
        public static string childSupport {
            get {
                return ResourceManager.GetString("childSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        public static string creditCards {
            get {
                return ResourceManager.GetString("creditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts / Loans.
        /// </summary>
        public static string debtsLoans {
            get {
                return ResourceManager.GetString("debtsLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit on property being purchased.
        /// </summary>
        public static string depositOnProperty {
            get {
                return ResourceManager.GetString("depositOnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance company loans and other debts.
        /// </summary>
        public static string financeCompanyLoansAndOtherDebts {
            get {
                return ResourceManager.GetString("financeCompanyLoansAndOtherDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Tax.
        /// </summary>
        public static string incomeTax {
            get {
                return ResourceManager.GetString("incomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease.
        /// </summary>
        public static string lease {
            get {
                return ResourceManager.GetString("lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Number(s) of Current Mortgage(s).
        /// </summary>
        public static string mortgageNumberOfCurrentMortgages {
            get {
                return ResourceManager.GetString("mortgageNumberOfCurrentMortgages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Worth (Total Assets - Total Liabilities).
        /// </summary>
        public static string netWorth {
            get {
                return ResourceManager.GetString("netWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Liability.
        /// </summary>
        public static string otherLiability {
            get {
                return ResourceManager.GetString("otherLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owing on Automobile.
        /// </summary>
        public static string owingOnAutomobile {
            get {
                return ResourceManager.GetString("owingOnAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRSP&apos;s.
        /// </summary>
        public static string rrsps {
            get {
                return ResourceManager.GetString("rrsps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Line of Credit.
        /// </summary>
        public static string secured {
            get {
                return ResourceManager.GetString("secured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks, bonds, mutual funds, etc..
        /// </summary>
        public static string stocksBondsMutualFunds {
            get {
                return ResourceManager.GetString("stocksBondsMutualFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Loans.
        /// </summary>
        public static string studentLoans {
            get {
                return ResourceManager.GetString("studentLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsecured Line of Credit.
        /// </summary>
        public static string unsecured {
            get {
                return ResourceManager.GetString("unsecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Present Home.
        /// </summary>
        public static string valueOfPresentHome {
            get {
                return ResourceManager.GetString("valueOfPresentHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Garnishment.
        /// </summary>
        public static string wageGarnishment {
            get {
                return ResourceManager.GetString("wageGarnishment", resourceCulture);
            }
        }
    }
}
