//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormAddress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormAddress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentumWebApplication.App_GlobalResources.FormAddress", typeof(FormAddress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string address1 {
            get {
                return ResourceManager.GetString("address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string address2 {
            get {
                return ResourceManager.GetString("address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string albertaSelect {
            get {
                return ResourceManager.GetString("albertaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allée.
        /// </summary>
        public static string allee {
            get {
                return ResourceManager.GetString("allee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoroute.
        /// </summary>
        public static string autoroute {
            get {
                return ResourceManager.GetString("autoroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenue.
        /// </summary>
        public static string avenue {
            get {
                return ResourceManager.GetString("avenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boulevard.
        /// </summary>
        public static string boulevard {
            get {
                return ResourceManager.GetString("boulevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        public static string britishColumbiaSelect {
            get {
                return ResourceManager.GetString("britishColumbiaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrefour.
        /// </summary>
        public static string carrefour {
            get {
                return ResourceManager.GetString("carrefour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string centre {
            get {
                return ResourceManager.GetString("centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cercle.
        /// </summary>
        public static string cercle {
            get {
                return ResourceManager.GetString("cercle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin.
        /// </summary>
        public static string chemin {
            get {
                return ResourceManager.GetString("chemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit.
        /// </summary>
        public static string circuit {
            get {
                return ResourceManager.GetString("circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town:.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côte.
        /// </summary>
        public static string cote {
            get {
                return ResourceManager.GetString("cote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cour.
        /// </summary>
        public static string cour {
            get {
                return ResourceManager.GetString("cour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cours.
        /// </summary>
        public static string cours {
            get {
                return ResourceManager.GetString("cours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string court {
            get {
                return ResourceManager.GetString("court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crescent.
        /// </summary>
        public static string crescent {
            get {
                return ResourceManager.GetString("crescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croissant.
        /// </summary>
        public static string croissant {
            get {
                return ResourceManager.GetString("croissant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échangeur.
        /// </summary>
        public static string echangeur {
            get {
                return ResourceManager.GetString("echangeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        public static string gate {
            get {
                return ResourceManager.GetString("gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île.
        /// </summary>
        public static string ile {
            get {
                return ResourceManager.GetString("ile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impasse.
        /// </summary>
        public static string impasse {
            get {
                return ResourceManager.GetString("impasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane.
        /// </summary>
        public static string lane {
            get {
                return ResourceManager.GetString("lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        public static string manitobaSelect {
            get {
                return ResourceManager.GetString("manitobaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montée.
        /// </summary>
        public static string montee {
            get {
                return ResourceManager.GetString("montee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brunswick.
        /// </summary>
        public static string newBrunswickSelect {
            get {
                return ResourceManager.GetString("newBrunswickSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland and Labrador.
        /// </summary>
        public static string newfoundlandSelect {
            get {
                return ResourceManager.GetString("newfoundlandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North East.
        /// </summary>
        public static string northEast {
            get {
                return ResourceManager.GetString("northEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North West.
        /// </summary>
        public static string northWest {
            get {
                return ResourceManager.GetString("northWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territories.
        /// </summary>
        public static string northwestTerritories {
            get {
                return ResourceManager.GetString("northwestTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia.
        /// </summary>
        public static string novaScotiaSelect {
            get {
                return ResourceManager.GetString("novaScotiaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunavut.
        /// </summary>
        public static string nunavutSelect {
            get {
                return ResourceManager.GetString("nunavutSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string ontarioSelect {
            get {
                return ResourceManager.GetString("ontarioSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateau.
        /// </summary>
        public static string plateau {
            get {
                return ResourceManager.GetString("plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointe.
        /// </summary>
        public static string pointe {
            get {
                return ResourceManager.GetString("pointe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prince Edward Island.
        /// </summary>
        public static string princeEdwardIslandSelect {
            get {
                return ResourceManager.GetString("princeEdwardIslandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promenade.
        /// </summary>
        public static string promenade {
            get {
                return ResourceManager.GetString("promenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province:.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string provinceSelect {
            get {
                return ResourceManager.GetString("provinceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quai.
        /// </summary>
        public static string quai {
            get {
                return ResourceManager.GetString("quai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string quebecSelect {
            get {
                return ResourceManager.GetString("quebecSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang.
        /// </summary>
        public static string rang {
            get {
                return ResourceManager.GetString("rang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string road {
            get {
                return ResourceManager.GetString("road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rond-Point.
        /// </summary>
        public static string rondpoint {
            get {
                return ResourceManager.GetString("rondpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        public static string rue {
            get {
                return ResourceManager.GetString("rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruelle.
        /// </summary>
        public static string ruelle {
            get {
                return ResourceManager.GetString("ruelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        public static string saskatchewanSelect {
            get {
                return ResourceManager.GetString("saskatchewanSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentier.
        /// </summary>
        public static string sentier {
            get {
                return ResourceManager.GetString("sentier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South East.
        /// </summary>
        public static string southEast {
            get {
                return ResourceManager.GetString("southEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South West.
        /// </summary>
        public static string southWest {
            get {
                return ResourceManager.GetString("southWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Direction:.
        /// </summary>
        public static string streetDirection {
            get {
                return ResourceManager.GetString("streetDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name:.
        /// </summary>
        public static string streetName {
            get {
                return ResourceManager.GetString("streetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Type:.
        /// </summary>
        public static string streetType {
            get {
                return ResourceManager.GetString("streetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrace.
        /// </summary>
        public static string terrace {
            get {
                return ResourceManager.GetString("terrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrasse.
        /// </summary>
        public static string terrasse {
            get {
                return ResourceManager.GetString("terrasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail.
        /// </summary>
        public static string trail {
            get {
                return ResourceManager.GetString("trail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voie.
        /// </summary>
        public static string voie {
            get {
                return ResourceManager.GetString("voie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way.
        /// </summary>
        public static string way {
            get {
                return ResourceManager.GetString("way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yukon.
        /// </summary>
        public static string yukonSelect {
            get {
                return ResourceManager.GetString("yukonSelect", resourceCulture);
            }
        }
    }
}
