//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormEmployer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormEmployer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentumWebApplication.App_GlobalResources.FormEmployer", typeof(FormEmployer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Income:.
        /// </summary>
        public static string annualIncome {
            get {
                return ResourceManager.GetString("annualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking/Finance.
        /// </summary>
        public static string bankingFinance {
            get {
                return ResourceManager.GetString("bankingFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerical.
        /// </summary>
        public static string clerical {
            get {
                return ResourceManager.GetString("clerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissions.
        /// </summary>
        public static string comissions {
            get {
                return ResourceManager.GetString("comissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string construction {
            get {
                return ResourceManager.GetString("construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farming/Natural Resources.
        /// </summary>
        public static string farmingNaturalResources {
            get {
                return ResourceManager.GetString("farmingNaturalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string government {
            get {
                return ResourceManager.GetString("government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Tech.
        /// </summary>
        public static string hightech {
            get {
                return ResourceManager.GetString("hightech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        public static string hourly {
            get {
                return ResourceManager.GetString("hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly + Commisions.
        /// </summary>
        public static string hourlyComissions {
            get {
                return ResourceManager.GetString("hourlyComissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Sector:.
        /// </summary>
        public static string industrySector {
            get {
                return ResourceManager.GetString("industrySector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour/Tradesperson.
        /// </summary>
        public static string labourTradesperson {
            get {
                return ResourceManager.GetString("labourTradesperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure/Entertainment.
        /// </summary>
        public static string leisureEntertainment {
            get {
                return ResourceManager.GetString("leisureEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Employment: (YYMM).
        /// </summary>
        public static string lengthOfEmployment {
            get {
                return ResourceManager.GetString("lengthOfEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string manufacturing {
            get {
                return ResourceManager.GetString("manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Employer:.
        /// </summary>
        public static string nameOfEmployer {
            get {
                return ResourceManager.GetString("nameOfEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation Type:.
        /// </summary>
        public static string occupationType {
            get {
                return ResourceManager.GetString("occupationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Employment Income.
        /// </summary>
        public static string otherEmploymentIncome {
            get {
                return ResourceManager.GetString("otherEmploymentIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Income Amount:.
        /// </summary>
        public static string otherIncomeAmount {
            get {
                return ResourceManager.GetString("otherIncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Income Source:.
        /// </summary>
        public static string otherIncomeSource {
            get {
                return ResourceManager.GetString("otherIncomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string professional {
            get {
                return ResourceManager.GetString("professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Sales.
        /// </summary>
        public static string retailSales {
            get {
                return ResourceManager.GetString("retailSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired.
        /// </summary>
        public static string retired {
            get {
                return ResourceManager.GetString("retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Employed.
        /// </summary>
        public static string selfemployed {
            get {
                return ResourceManager.GetString("selfemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string transportation {
            get {
                return ResourceManager.GetString("transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Income:.
        /// </summary>
        public static string typeOfIncome {
            get {
                return ResourceManager.GetString("typeOfIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varies.
        /// </summary>
        public static string varies {
            get {
                return ResourceManager.GetString("varies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years in Line of Business: (YYMM).
        /// </summary>
        public static string yearsInBussines {
            get {
                return ResourceManager.GetString("yearsInBussines", resourceCulture);
            }
        }
    }
}
