//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentumWebApplication.CentumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://centum.ca/webservices", ConfigurationName="CentumService.CentumWebServiceSoap")]
    public interface CentumWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://centum.ca/webservices/GetAgentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CentumWebApplication.CentumService.User GetAgentDetails(string firmCode, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://centum.ca/webservices/GetAgentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CentumWebApplication.CentumService.User> GetAgentDetailsAsync(string firmCode, string userId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://centum.ca/webservices")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string officeNameField;
        
        private string officeCityField;
        
        private string officeProvField;
        
        private string nameFirstField;
        
        private string nameLastField;
        
        private string agentEmailField;
        
        private string agentLanguageField;
        
        private string firmCodeSubmitField;
        
        private string expertIdSubmitField;
        
        private string disclosureUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OfficeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
                this.RaisePropertyChanged("OfficeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OfficeCity {
            get {
                return this.officeCityField;
            }
            set {
                this.officeCityField = value;
                this.RaisePropertyChanged("OfficeCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OfficeProv {
            get {
                return this.officeProvField;
            }
            set {
                this.officeProvField = value;
                this.RaisePropertyChanged("OfficeProv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NameFirst {
            get {
                return this.nameFirstField;
            }
            set {
                this.nameFirstField = value;
                this.RaisePropertyChanged("NameFirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NameLast {
            get {
                return this.nameLastField;
            }
            set {
                this.nameLastField = value;
                this.RaisePropertyChanged("NameLast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AgentEmail {
            get {
                return this.agentEmailField;
            }
            set {
                this.agentEmailField = value;
                this.RaisePropertyChanged("AgentEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AgentLanguage {
            get {
                return this.agentLanguageField;
            }
            set {
                this.agentLanguageField = value;
                this.RaisePropertyChanged("AgentLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FirmCodeSubmit {
            get {
                return this.firmCodeSubmitField;
            }
            set {
                this.firmCodeSubmitField = value;
                this.RaisePropertyChanged("FirmCodeSubmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ExpertIdSubmit {
            get {
                return this.expertIdSubmitField;
            }
            set {
                this.expertIdSubmitField = value;
                this.RaisePropertyChanged("ExpertIdSubmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DisclosureUrl {
            get {
                return this.disclosureUrlField;
            }
            set {
                this.disclosureUrlField = value;
                this.RaisePropertyChanged("DisclosureUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CentumWebServiceSoapChannel : CentumWebApplication.CentumService.CentumWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentumWebServiceSoapClient : System.ServiceModel.ClientBase<CentumWebApplication.CentumService.CentumWebServiceSoap>, CentumWebApplication.CentumService.CentumWebServiceSoap {
        
        public CentumWebServiceSoapClient() {
        }
        
        public CentumWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentumWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentumWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentumWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CentumWebApplication.CentumService.User GetAgentDetails(string firmCode, string userId) {
            return base.Channel.GetAgentDetails(firmCode, userId);
        }
        
        public System.Threading.Tasks.Task<CentumWebApplication.CentumService.User> GetAgentDetailsAsync(string firmCode, string userId) {
            return base.Channel.GetAgentDetailsAsync(firmCode, userId);
        }
    }
}
